services:
    - type: cron
      name: Price Alert Scraper
      schedule: '0 */6 * * *'
      env: node
      buildCommand: ''
      startCommand: node src/jobs/cronRunner.js
      envVarsFromGroup: common-env

    - type: cron
      name: Full Product Rescrape
      schedule: '0 0 * * *'
      env: node
      buildCommand: ''
      startCommand: node src/jobs/cronDailyRunner.js
      envVarsFromGroup: common-env

    - type: worker
      name: Notification Worker
      env: node
      buildCommand: ''
      startCommand: node src/jobs/notificationWorkerRunner.js
      envVarsFromGroup: common-env
