version: 1

services:
    - type: web
      name: Smart Shopping API
      runtime: node
      region: frankfurt
      buildCommand: npm install
      startCommand: node server.js
      envVars:
          - fromGroup: common-env

    - type: worker
      name: Notification Worker
      runtime: node
      region: frankfurt
      buildCommand: npm install
      startCommand: node src/jobs/workers/notificationWorkerRunner.js
      envVars:
          - fromGroup: common-env
