version: 1

services:
    - type: web
      name: Smart Shopping API
      runtime: node
      region: frankfurt
      buildCommand: npm install
      startCommand: node server.js
      envVars:
          - fromGroup: common-env

    - type: cron
      name: Price Alert Scraper
      runtime: node
      region: frankfurt
      schedule: '0 */6 * * *'
      buildCommand: npm install
      startCommand: node jobs/scheduler/cronRunner.js
      envVars:
          - fromGroup: common-env

    - type: cron
      name: Full Product Rescrape
      runtime: node
      region: frankfurt
      schedule: '0 0 * * *'
      buildCommand: npm install
      startCommand: node jobs/scheduler/cronDailyRunner.js
      envVars:
          - fromGroup: common-env

    - type: worker
      name: Notification Worker
      runtime: node
      region: frankfurt
      buildCommand: npm install
      startCommand: node jobs/workers/notificationWorkerRunner.js
      envVars:
          - fromGroup: common-env
