export const mockOttoScraper = async (query) => {
    return [
        {
            title: 'iPhone 15 schwarz',
            price: '730.99',
            currency: '€',
            brand: 'Apple',
            availability: '1',
            storage_gb: 128,
            productSellerRate: '4.1',
            link: 'https://www.otto.de/p/apple-iphone-15-smartphone-15-5-cm-6-1-zoll-128-gb-speicherplatz-48-mp-kamera-1786938266/#variationId=1786938267',
            image: 'https://i.otto.de/i/otto/c623588c-6bde-5271-b109-60bc10d199bb?$respon',
            seller: 'Apple',
            productSellerRate: '0',
            badge: 'no info',
            isPrime: true,
            delivery: 'lieferbar in 4 Wochen',
            store: 'Otto',
            availability: '1',
            seller_rating: '4.5',
        },

        {
            title: 'iPhone 16 Weiß',
            price: '827.99',
            currency: '€',
            brand: 'Apple',
            availability: '1',
            storage_gb: 128,
            productSellerRate: '3.7',
            link: 'https://www.otto.de/p/apple-iphone-16-smartphone-15-54-cm-6-12-zoll-512-gb-speicherplatz-48-mp-kamera-1909231538/#variationId=1909231539',
            image: 'https://i.otto.de/i/otto/5364ccf3-0769-5c4f-b066-17da79e44232?$respon',
            seller: 'Apple',
            productSellerRate: '0',
            badge: 'no info',
            isPrime: true,
            delivery: 'lieferbar in 3 Wochen',
            store: 'Otto',
            availability: '1',
            seller_rating: '3.2',
        },

        {
            title: 'iPhone 16 Pro Titan',
            price: '1049.00',
            currency: '€',
            brand: 'Apple',
            availability: '1',
            storage_gb: 128,
            productSellerRate: '4.8',
            link: 'https://www.otto.de/p/apple-iphone-16-pro-smartphone-15-9-cm-6-3-zoll-1000-gb-speicherplatz-48-mp-kamera-1909231815/#variationId=1909231863',
            image: 'https://www.otto.de/p/apple-iphone-16-pro-smartphone-15-9-cm-6-3-zoll-1000-gb-speicherplatz-48-mp-kamera-1909231815/#variationId=1909231863',
            seller: 'Apple',
            productSellerRate: '0',
            badge: 'no info',
            isPrime: true,
            delivery: 'lieferbar in 3 Wochen',
            store: 'Otto',
            availability: '1',
            seller_rating: '4.8',
        },

        {
            title: 'iPhone 15 Pink',
            price: '730.99',
            currency: '€',
            brand: 'Apple',
            availability: '1',
            storage_gb: 128,
            productSellerRate: '4.4',
            link: 'https://www.otto.de/p/apple-iphone-15-smartphone-15-5-cm-6-1-zoll-128-gb-speicherplatz-48-mp-kamera-1786938266/#variationId=1786938299',
            image: 'https://i.otto.de/i/otto/71d06c37-38a3-5cf8-b2cd-a69d93e59fa3?$respon',
            seller: 'Apple',
            productSellerRate: '0',
            badge: 'no info',
            isPrime: true,
            delivery: 'lieferbar - in 1-2 Werktagen bei dir',
            store: 'Otto',
            availability: '1',
            seller_rating: '4.5',
        },

        {
            title: 'iPhone 16 Weiß',
            price: '827.99',
            currency: '€',
            brand: 'Apple',
            availability: '1',
            storage_gb: 128,
            productSellerRate: '4.0',
            link: 'https://www.otto.de/p/apple-iphone-16-smartphone-15-54-cm-6-12-zoll-512-gb-speicherplatz-48-mp-kamera-1909231538/#variationId=1909231539',
            image: 'https://i.otto.de/i/otto/3dec8c0e-ee93-5eef-b3e4-3eecb7e6e518?$respon',
            seller: 'Apple',
            productSellerRate: '0',
            badge: 'no info',
            isPrime: true,
            delivery: 'lieferbar - in 1-2 Werktagen bei dir',
            store: 'Otto',
            availability: '1',
            seller_rating: '4.7',
        },
        {
            title: 'iPhone 14 Plus Pink',
            price: '759,00',
            currency: '€',
            brand: 'Apple',
            availability: '1',
            storage_gb: 128,
            productSellerRate: '4.0',
            link: 'https://www.otto.de/p/apple-iphone-14-plus-smartphone-17-cm-6-7-zoll-128-gb-speicherplatz-12-mp-kamera-1676826906/#variationId=1676024479',
            image: 'https://i.otto.de/i/otto/5c758f40-1ffc-5ed7-962c-7a379ba367d9?h=520&w=551&sm=clamp&upscale=true&fmt=auto',
            seller: 'Apple',
            productSellerRate: '0',
            badge: 'no info',
            isPrime: true,
            delivery: 'lieferbar - in 1-2 Werktagen bei dir',
            store: 'Otto',
            availability: '1',
            seller_rating: '4.6',
        },

        {
            title: 'iPhone 16 Plus Pink',
            price: '974.99',
            currency: '€',
            brand: 'Apple',
            availability: '1',
            storage_gb: 128,
            productSellerRate: '4.3',
            link: 'https://www.otto.de/p/apple-iphone-16-plus-smartphone-17-cm-6-7-zoll-128-gb-speicherplatz-48-mp-kamera-1909231696/#variationId=1909231760',
            image: 'https://i.otto.de/i/otto/ed774b2a-37cd-59e9-8b3d-cb4b18e82974?h=520&w=551&sm=clamp&upscale=true&fmt=auto',
            seller: 'Apple',
            productSellerRate: '0',
            badge: 'no info',
            isPrime: true,
            delivery: 'lieferbar in 3 Wochen',
            store: 'Otto',
            availability: '1',
            seller_rating: '4.8',
        },

        {
            title: 'iPhone 16e schwarz',
            price: '829,00',
            currency: '€',
            brand: 'Apple',
            availability: '1',
            storage_gb: 128,
            productSellerRate: '4.2',
            link: 'https://www.otto.de/p/apple-iphone-16e-smartphone-15-4-cm-6-1-zoll-512-gb-speicherplatz-48-mp-kamera-1957733663/#variationId=1957733672',
            image: 'https://www.otto.de/p/apple-iphone-16e-smartphone-15-4-cm-6-1-zoll-512-gb-speicherplatz-48-mp-kamera-1957733663/#variationId=1957733672',
            seller: 'Apple',
            productSellerRate: '0',
            badge: 'no info',
            isPrime: true,
            delivery: 'lieferbar - in 6-8 Werktagen bei dir',
            store: 'Otto',
            availability: '1',
            seller_rating: '4.3',
        },

        {
            title: 'iPhone 15 Plus grün',
            price: '827.99',
            currency: '€',
            brand: 'Apple',
            availability: '1',
            storage_gb: 128,
            productSellerRate: '4.8',
            link: 'https://www.otto.de/p/apple-iphone-15-plus-smartphone-17-cm-6-7-zoll-128-gb-speicherplatz-48-mp-kamera-1786937979/#variationId=1786938029',
            image: 'https://i.otto.de/i/otto/3d61492e-5b05-5a22-b9df-08cd5267ead0?h=520&w=551&sm=clamp&upscale=true&fmt=auto',
            seller: 'Apple',
            productSellerRate: '0',
            badge: 'no info',
            isPrime: true,
            delivery: 'lieferbar - in 1-2 Werktagen bei dir',
            store: 'Otto',
            availability: '1',
            seller_rating: '4.1',
        },
        {
            title: 'iPhone 14 Plus Pink',
            price: '846.35',
            currency: '€',
            brand: 'Apple',
            availability: '1',
            storage_gb: 128,
            productSellerRate: '4.9',
            link: 'https://www.otto.de/p/apple-iphone-14-plus-smartphone-17-cm-6-7-zoll-128-gb-speicherplatz-12-mp-kamera-1676826906/#variationId=1676024479',
            image: 'https://i.otto.de/i/otto/5c758f40-1ffc-5ed7-962c-7a379ba367d9?h=520&w=551&sm=clamp&upscale=true&fmt=auto',
            seller: 'Apple',
            productSellerRate: '0',
            badge: 'no info',
            isPrime: true,
            delivery: 'lieferbar - in 1-2 Werktagen bei dir',
            store: 'Otto',
            availability: '1',
            seller_rating: '4.4',
        },
        {
            title: 'iPhone 16 black',
            price: '827,99',
            currency: '€',
            brand: 'Apple',
            availability: '1',
            storage_gb: 128,
            productSellerRate: '4.6',
            link: 'https://www.ebay.de/itm/375861588585?_skw=iphone+13&epid=2320328646&itmmeta=01JRWCJZABVW9P4BHFZK72EW4F&hash=item578',
            image: 'https://i.otto.de/i/otto/f4a318ef-e316-5328-8be4-f0cc1564408c?$respon',
            seller: 'Apple',
            productSellerRate: '0',
            badge: 'no info',
            isPrime: true,
            delivery: 'lieferbar - in 1-2 Werktagen bei dir',
            store: 'Otto',
            availability: '1',
            seller_rating: '4.2',
        },
        {
            title: 'Samsung Galaxy S24 Black',
            price: '709.99',
            currency: '€',
            brand: 'Samsung',
            availability: '1',
            storage_gb: 128,
            productSellerRate: '4.7',
            link: 'https://www.otto.de/p/samsung-galaxy-s24-smartphone-15-64-cm-6-2-zoll-256-gb-speicherplatz-50-mp-kamera-ai-funktionen-1823699265/#variationId=1823699282',
            image: 'https://i.otto.de/i/otto/727a3c52-f9f6-5593-8d06-742237519227?$respon',
            seller: 'Samsung',
            productSellerRate: '0',
            badge: 'no info',
            isPrime: true,
            delivery: 'lieferbar - in 1-2 Werktagen bei dir',
            store: 'Otto',
            availability: '1',
            seller_rating: '3.7',
        },

        {
            title: 'Samsung Galaxy S22',
            price: '709,99',
            currency: '€',
            brand: 'Samsung',
            availability: '1',
            storage_gb: 128,
            productSellerRate: '5.0',
            link: 'https://www.otto.de/p/samsung-galaxy-s24-smartphone-15-64-cm-6-2-zoll-256-gb-speicherplatz-50-mp-kamera-ai-funktionen-1823699265/#variationId=1823699282',
            image: 'https://i.otto.de/i/otto/727a3c52-f9f6-5593-8d06-742237519227?h=520&w=551&sm=clamp&upscale=true&fmt=auto',
            seller: 'Samsung',
            productSellerRate: '0',
            badge: 'no info',
            isPrime: true,
            delivery: 'lieferbar - in 2-3 Werktagen bei dir',
            store: 'Otto',
            availability: '1',
            seller_rating: '3.5',
        },
    ];
};
